import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>CloneTube</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://cdn3.iconfinder.com/data/icons/social-network-30/512/social-06-512.png"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Oswald&display=swap"
        />
      </Head>

      <main className="flex flex-col items-center justify-center"></main>
    </>
  );
}
