import Head from "next/head";
import Category from "~/components/Category";
import Video from "~/components/Video";

export default function Home({ shortMenu }: { shortMenu: boolean }) {
  return (
    <>
      <Head>
        <title>CloneTube</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="icon"
          href="https://cdn3.iconfinder.com/data/icons/social-network-30/512/social-06-512.png"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Oswald&display=swap"
        />
      </Head>

      <main
        className={`flex flex-col px-6 pt-2 ${shortMenu ? "w-[85rem]" : "w-[73rem]"}`}
      >
        <Category shortMenu={shortMenu} />

        <div className={`flex w-full flex-wrap gap-x-5 gap-y-10 py-5`}>
          <Video shortMenu={shortMenu} />
        </div>
      </main>
    </>
  );
}
